#!/bin/bash

ru_sites=(
# Russian
yandex.ru
habr.com
lib.ru
auto.ru
wikipedia.ru
reg.ru
sberdevices.ru
# Chinese
z.ai
# Github (140.82.112.0/20) is still available and popular. save on intl traffic.
# it must be added with "ru-routes.sh add include 140.82.112.0/20"
github.com
""
)

sber_sites=(
# sberdevices
git.sberdevices.ru
tasks.sberdevices.ru
confluence.sberdevices.ru
""
)

other_sites=(
# rest of the world
google.com
claude.ai
nordicsemi.com
cppreference.com
""
)

test_route_table() {
  table=$1
  shift
  while true; do
    site="$1"
    shift
    [ -z "$site" ] && break
    echo -n "tesing $site ... "
    [ "$(ip route get $(dig +short $site | tail -1) | grep -o "table $table")" == "table $table" ] && echo "OK" || echo "failed to route $site with $table"
  done
}

echo -n "Testing Russian sites with Russian routing ... "
test_route_table ru_routes "${ru_sites[@]}" | grep -q "failed" && echo "TESTS FAILED" || echo "TESTS PASSED"
echo -n "Testing non-Russian sites with Russian routing ... "
test_route_table ru_routes "${other_sites[@]}" | grep -q "OK" && echo "TESTS FAILED" || echo "TESTS PASSED"
echo -n "Testing sber sites with Sber routing ... "
test_route_table sber_cloud_tun "${sber_sites[@]}" | grep -q "failed" && echo "TESTS FAILED" || echo "TESTS PASSED"
echo -n "Testing non-Russian sites with Sber routing ... "
test_route_table sber_cloud_tun "${other_sites[@]}" | grep -q "OK" && echo "TESTS FAILED" || echo "TESTS PASSED"
